# Generated by Django 4.1.4 on 2022-12-20 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shopping", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField()),
                ("create_time", models.DateTimeField(verbose_name="create time")),
                (
                    "accept_time",
                    models.DateTimeField(null=True, verbose_name="accept time"),
                ),
                (
                    "payment_time",
                    models.DateTimeField(null=True, verbose_name="payment time"),
                ),
                (
                    "shipping_time",
                    models.DateTimeField(null=True, verbose_name="shipping time"),
                ),
                (
                    "last_update_time",
                    models.DateTimeField(verbose_name="last update time"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shopping.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
