# Generated by Django 4.1.4 on 2022-12-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0002_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
